# Generated by Django 2.0.5 on 2019-09-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bancos',
            old_name='producto',
            new_name='tipo_producto',
        ),
    ]
