# Generated by Django 2.0.5 on 2019-09-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20190929_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancos',
            name='interes',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bancos',
            name='moneda',
            field=models.CharField(max_length=10),
        ),
    ]
